-- CREACIÓN DE BASE DE DATOS
CREATE DATABASE IF NOT EXISTS BANKING_TCS;
USE BANKING_TCS;

-- CREACIÓN DE LAS TABLAS

-- Tabla PERSON
CREATE TABLE IF NOT EXISTS PERSON (
    PERSON_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    GENDER VARCHAR(20),
    AGE INT,
    IDENTIFICATION VARCHAR(20) UNIQUE NOT NULL,
    ADDRESS VARCHAR(200),
    PHONE VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Tabla CLIENT
CREATE TABLE IF NOT EXISTS CLIENT (
    CLIENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PERSON_ID BIGINT NOT NULL,
    CLIENT_CODE VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    STATUS BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Tabla ACCOUNT
CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    ACCOUNT_TYPE VARCHAR(30) NOT NULL COMMENT 'AHORRO, CORRIENTE, ETC',
    CURRENT_BALANCE DECIMAL(15,2) NOT NULL,
    STATUS BOOLEAN DEFAULT TRUE,
    CLIENT_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Tabla MOVEMENT_TRANSACTION
CREATE TABLE IF NOT EXISTS MOVEMENT_TRANSACTION (
    TRANSACTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL COMMENT 'DEPOSITO, RETIRO',
    AMOUNT DECIMAL(15,2) NOT NULL,
    BALANCE DECIMAL(15,2) NOT NULL,
    ACCOUNT_ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- CREACIÓN DE ÍNDICES PARA MEJORAR EL RENDIMIENTO
CREATE INDEX idx_client_person ON CLIENT(PERSON_ID);
CREATE INDEX idx_account_client ON ACCOUNT(CLIENT_ID);
CREATE INDEX idx_movement_account ON MOVEMENT_TRANSACTION(ACCOUNT_ID);
CREATE INDEX idx_movement_date ON MOVEMENT_TRANSACTION(TRANSACTION_DATE);